Support multiple keys splitted by '||'
adorechic/secret_env pull request #3
Opened 2016-11-29 02:20 UTC by winebarrel

Add support for multiple keys:

```ruby
ENV['DB_USER'] = nil
ENV['DB_USER2'] = "db_user2"

# "#{DB_USER || DB_USER2}@..." => "db_user2@..."
```

2016-11-29 05:00 UTC, adorechic requested changes

2016-11-29 05:00 UTC, adorechic commented on lib/secret_env.rb
> +        secret_keys.split(/\s*\|\|\s*/).each do |secret_key|
I think this splitting may contain unnecessary spaces

```ruby
irb(main):005:0> " db_password || db_password2".split(/\s*\|\|\s*/)
=> [" db_password", "db_password2"]
```

How about this?

```ruby
irb(main):003:0> "db_password || db_password2".split("||").map(&:strip)
=> ["db_password", "db_password2"]
```

2016-11-29 09:09 UTC, winebarrel commented on lib/secret_env.rb
> +        secret_keys.split(/\s*\|\|\s*/).each do |secret_key|
> How about this?

Looks good. :-)
FIxed d529ad3

2016-11-30 02:42 UTC, adorechic approved these changes

2016-11-30 02:42 UTC, merged

2016-11-30 02:45 UTC, adorechic commented
https://rubygems.org/gems/secret_env/versions/0.4.0

2016-11-30 02:53 UTC, winebarrel commented
Thanks!